# Generated by Django 5.0.7 on 2024-11-21 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_product_images_images_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.product'),
        ),
    ]
